# Generated by Django 3.1.6 on 2021-02-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Event name')),
                ('start_date', models.DateField(blank=True)),
                ('duration', models.IntegerField(blank=True, default=1)),
                ('landing_page', models.CharField(max_length=100)),
                ('scrape_ready', models.BooleanField(blank=True, default=False)),
                ('category', models.ManyToManyField(to='core.Category')),
            ],
        ),
        migrations.CreateModel(
            name='EventTpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('schedule_path', models.CharField(blank=True, max_length=20, null=True, verbose_name='Schedule path')),
                ('css_link_button', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button (CSS)')),
                ('css_image', models.CharField(blank=True, max_length=50, null=True, verbose_name='Photo (CSS)')),
                ('css_talk_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title (CSS)')),
                ('css_talk_topics', models.CharField(blank=True, max_length=50, null=True, verbose_name='list of topics (CSS)')),
                ('css_speaker_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Speaker name (CSS)')),
                ('css_audio_file', models.CharField(blank=True, max_length=50, null=True, verbose_name='Audio file (CSS)')),
                ('css_video_file', models.CharField(blank=True, max_length=50, null=True, verbose_name='Video file (CSS)')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TalkSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Session name')),
                ('audio_file_path', models.URLField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.speaker', verbose_name='Speaker name')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_tpl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventtpl'),
        ),
    ]
