# Generated by Django 3.1.6 on 2021-02-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talksession',
            name='audio_file_path',
        ),
        migrations.AddField(
            model_name='talksession',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='talksession',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='talksession',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, upload_to='mp3s'),
        ),
        migrations.AddField(
            model_name='talksession',
            name='mp3_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtpl',
            name='css_talk_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title (CSS)'),
        ),
        migrations.AlterField(
            model_name='eventtpl',
            name='css_talk_topics',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='List of topics (CSS)'),
        ),
    ]
