# Generated by Django 3.1.6 on 2021-02-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='css_image',
            field=models.CharField(blank=True, max_length=20, verbose_name='Photo (CSS)'),
        ),
        migrations.AddField(
            model_name='event',
            name='css_talk_session',
            field=models.CharField(blank=True, max_length=20, verbose_name='Talk title (CSS)'),
        ),
        migrations.AddField(
            model_name='event',
            name='css_video_file',
            field=models.CharField(blank=True, max_length=20, verbose_name='Video file (CSS)'),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.CharField(blank=True, max_length=20, verbose_name='Schedule path'),
        ),
        migrations.AlterField(
            model_name='event',
            name='css_audio_file',
            field=models.CharField(blank=True, max_length=20, verbose_name='Audio file (CSS)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='css_link_button',
            field=models.CharField(blank=True, max_length=20, verbose_name='Button link (CSS)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='landing_page',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Event name'),
        ),
    ]
