# Generated by Django 3.1.6 on 2021-02-13 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210213_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talksession',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event'),
        ),
        migrations.AlterField(
            model_name='talksession',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talksession',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Session name'),
        ),
        migrations.AlterField(
            model_name='talksession',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.speaker', verbose_name='Speaker name'),
        ),
    ]
