# Generated by Django 3.1.6 on 2021-02-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210213_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='talksession',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='talksession',
            name='image_url',
        ),
        migrations.AddField(
            model_name='speaker',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='photo file'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='img_url',
            field=models.URLField(blank=True, null=True, verbose_name='photo remote url'),
        ),
        migrations.AlterField(
            model_name='talksession',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, upload_to='mp3s', verbose_name='mp3 file'),
        ),
        migrations.AlterField(
            model_name='talksession',
            name='mp3_url',
            field=models.URLField(blank=True, null=True, verbose_name='mp3 remote url'),
        ),
    ]
